<?php
/**
 * Functionality for the WP Admin Plugin Options page
 *    WP Admin > Settings > Wix Migration Tool
 *
 * This file contains PHP.
 *
 * @link        http://dotherightthing.co.nz
 * @since       0.1.0
 *
 * @package     Wp_Wix_Migration_Tool
 * @subpackage  Wp_Wix_Migration_Tool/app
 */

if ( !function_exists( 'wp_wix_migration_tool_menu' ) ) {


  /**
   * Display a link to the options page in the admin menu
   *
   * @since       0.1.0
   * @uses        ../../../../wp-admin/includes/plugin.php
   * @see         https://developer.wordpress.org/reference/functions/add_options_page/
   */
  function wp_wix_migration_tool_menu() {

    add_options_page(
      'Wix Migration Tool',
      'Wix Migration Tool',
      'manage_options',
      'wix-migration-tool',
      'wp_wix_migration_tool_options_page'
    );
  }

  add_action('admin_menu', 'wp_wix_migration_tool_menu');

}

/**
 * Create the plugin options page
 */
if ( !function_exists( 'wp_wix_migration_tool_options_page' ) ) {

  /**
   * Render the appropriate UI on Settings > Wix Migration Tool
   *
   *    1. Take the user's selection (from the form input)
   *    2. Request the data from the API
   *    3. Store 3 pieces of data in the options table:
   *       a. The user's selection: 'wp_wix_migration_tool_datatype',
   *          so that the dataset can be regenerated after a specified amount of time
   *       b. The data set generated by the API: 'wp_wix_migration_tool_data'
   *       c. The time that the data set was generated: 'last_updated'
   *    4. Render the options page
   *
   *    Note: Shortcode/widget options are specific to each instance of the shortcode/widget
   *    and are thus stored with those individual instances.
   *
   * @since       0.1.0
   */
  function wp_wix_migration_tool_options_page() {

    if ( ! current_user_can( 'manage_options' ) ) {
      wp_die( 'Sorry, you do not have sufficient permissions to access this page.' );
    }

    /**
     * Make this global available within the required statement
     */
    global $wp_wix_migration_tool_options;

    if ( isset( $_POST['wp_wix_migration_tool_form_submitted'] ) ) {

      // check that the form submission was legitimate
      $hidden_field = esc_html( $_POST['wp_wix_migration_tool_form_submitted'] );

      if ( $hidden_field === 'Y' ) {

        // 1. get user preferences from form submission
        $wp_wix_migration_tool_datatype = esc_html( $_POST['wp_wix_migration_tool_datatype'] );

        // 2. send user preferences to API to get results
        $wp_wix_migration_tool_data = wp_wix_migration_tool_data_get(
          $wp_wix_migration_tool_datatype
        );

        // 3a. store user preferences in options object
        $wp_wix_migration_tool_options['wp_wix_migration_tool_datatype'] = $wp_wix_migration_tool_datatype;

        // 3b. store API results in options object
        $wp_wix_migration_tool_options['wp_wix_migration_tool_data'] = $wp_wix_migration_tool_data;

        // 3c. store timestamp in options object
        $wp_wix_migration_tool_options['last_updated'] = time(); // UNIX timestamp for the current time

        /**
         * Save options object to database
         *
         * Update the plugin data stored in the WP Options table
         * This function may be used in place of add_option, although it is not as flexible.
         * update_option will check to see if the option already exists.
         * If it does not, it will be added with add_option('option_name', 'option_value').
         * Unless you need to specify the optional arguments of add_option(),
         * update_option() is a useful catch-all for both adding and updating options.
         * @example update_option( string $option, mixed $value, string|bool $autoload = null )
         * @see https://codex.wordpress.org/Function_Reference/update_option
         */
        update_option( 'wp_wix_migration_tool', $wp_wix_migration_tool_options, null );
      }
    }

    /**
     * Load the plugin data stored in the WP Options table
     * Retrieves an option value based on an option name.
     * @example get_option( string $option, mixed $default = false )
     */
    $wp_wix_migration_tool_options = get_option( 'wp_wix_migration_tool' );

    // if options have been stored, recover them
    if ( $wp_wix_migration_tool_options !== '' ) {
      $wp_wix_migration_tool_datatype = $wp_wix_migration_tool_options['wp_wix_migration_tool_datatype'];
      $wp_wix_migration_tool_data = $wp_wix_migration_tool_options['wp_wix_migration_tool_data'];
    }

    /**
     * 4. Load the HTML template
     * This function's variables will be available to this template.
     * @todo display the last generated timestamp on the options page
     */
    require_once(WP_WIX_MIGRATION_TOOL_PATH . 'views/admin/partials/wp-wix-migration-tool-options-page.php');
  }

}

?>
